config/routes.rb
IdeaGen::Application.routes.draw do
  resources :posts

  resources :users

  match 'post/vote', :to=> 'posts#vote_post'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title, :user_id, :votes
  belongs_to :user
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :user_num
  has_many :posts, :primary_key=>"user_num", :foreign_key=>"user_id"

  def number_name
  	self.user_num.to_s + " " + self.name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order("votes DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    @post.votes = 0

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  def vote_post
    @post = Post.find(params[:id])
    puts "DIRECTION", params[:direction]
    if params[:direction].to_i==1
      puts 'incrementing'
      @post.increment!(:votes)
    else 
      puts "decrementing"
      @post.decrement!(:votes)
    end

    redirect_to posts_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IdeaGen</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "jquery.js" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class='container'>
		<%= yield %>
	</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, :size=>84 %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, :cols=>60, :rows=>4 %>
  </div>
  <div class="field">
    <%= collection_select(:post, :user_id, User.all, :user_num, :number_name, {:prompt=>"Select your name"}, html_options={:class => 'author-select'}) %>
    <div class="hide-field">
      <%= f.label :user_id %><br />
      <%= f.text_field :user_id, :class=>"user_id_set" %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript">

$('#post_user_id').change(function(){
                    var selected = $('#post_user_id').find(':selected').val().split(' ');
                    $('.user_id_set').val(selected[0])
                  })

</script>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class='list-space'>
  <div class='row-fluid'>
  <h1 class='span8 pull-left'>Ideas</h1> 

  <button class="btn btn-success new-post span3 pull-right"><%= link_to 'New Post', new_post_path %></button>
  </div>

  <br>
  <br>

  <% @posts.each do |post| %>
    <div class='row-fluid'>
      <div class='well'>
        <div id="show<%= post.id %>"></div>
        <div class='span12 idea-head'><%= post.title %></div> 
        <br>
        <br>
        <br>
        Posted by: <%= post.user.name %> on <%= post.created_at.month %>/<%= post.created_at.day %>
        <br>
        <br>
        <div class='span12'>
          <a href="#show<%= post.id %>" data-pass="<%= post.id %>" id='post-button<%= post.id %>'><b>Read more...</b></a>
        </div>
        <br>
        <div class="span9 pull-left">
          <%= link_to 'Edit post', edit_post_path(post), :style=>"font-size:8px;"%>
        </div>
        <div class="span2 pull-right">
          <%= link_to "", post_vote_path(:id=>post.id, :direction=>1), :class=>"icon-arrow-up" %> <%= link_to "", post_vote_path(:id=>post.id, :direction=>0), :class=>"icon-arrow-down" %> (<%= post.votes %>)
        </div>
        <br>
        <script type="text/javascript">
          var $div_on = $('#post-button<%= post.id %>')

          $div_on.click(function(){
            if($('.show<%= post.id %>').is(":hidden")){
              $('.show<%= post.id %>').show(1000)
            }
            else{
              $('.show<%= post.id %>').hide()
            }
          })
        </script>
      </div>
    </div>
    <div class='row-fluid show-content show<%= post.id %>'>
      <div class='content-space'>
        <h4><%= post.title %></h4>
        <%= post.content %>
      </div>
    </div>
  <% end %>

  <br />
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>

<p>
  <b>Votes:</b>
  <%= @post.votes %>
</p>

<p>
  <b>User:</b>
  <%= @post.user_id %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/posts/vote_post.html.erb
<h1> hello </h1>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>